version: "3.8"

services:
  maps-app:
    build: .
    container_name: maps-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
      - /app/backend/node_modules
    restart: unless-stopped
    environment:
      - SKIP_IMPORT=points
