version: "3.8"

services:
  maps-app:
    build: .
    container_name: maps-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/daten.csv:/app/backend/daten.csv
    restart: unless-stopped

  fuseki-hdt:
    image: 'rogargon/fuseki-hdt-docker:latest'
    ports:
        - '3030:3030'
    volumes:
        - './data/dnb-all.hdt:/data/dataset.hdt:ro'
